name: build-mac

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@11.1.2 --activate

      - name: Check pnpm
        run: pnpm --version

      - name: Install deps
        run: corepack pnpm install

      - name: Build DMG
        run: corepack pnpm dist:mac

      - name: Build ZIP
        run: corepack pnpm dist:mac:zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CBTA44_SYS-mac
          path: release/*
