name: build-mac

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'

      - name: Enable corepack
        run: corepack enable

      - name: Install pnpm
        run: npm install -g pnpm@11.1.2 --force

      - name: Check pnpm
        run: pnpm --version

      - name: Install deps
        run: pnpm install

      - name: Build DMG
        run: pnpm dist:mac

      - name: Build ZIP
        run: pnpm dist:mac:zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CBTA44_SYS-mac
          path: release/*
